### ISSUE TITLE
Can't build with new electron-builder after 19.56

### ISSUE THREAD

**Issue by loreberti89** [vuetifyjs/electron#19]
##### Describe the issue / bug.
\#
I can't build with the new versions of electron-builder.

##### How can I reproduce this problem?
\#
Set electron-builder version : "^20.34.0"

##### If visual, provide a screenshot.
\#
The log of error is:

> Error: C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-bin\win\x64\app-builder.exe exited with code 1
>     at ChildProcess.childProcess.once.code (C:\Users\Lorenzo\Documents\testElect
> ron\my-project\node_modules\builder-util\src\util.ts:244:14)
>     at Object.onceWrapper (events.js:317:30)
>     at emitTwo (events.js:126:13)
>     at ChildProcess.emit (events.js:214:7)
>     at maybeClose (internal/child_process.js:915:16)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
> From previous event:
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.signAndEditResources (C:\Users\Lorenzo\Documents\testElectron
> \my-project\node_modules\app-builder-lib\src\winPackager.ts:251:158)
>     at _bluebirdLst.default.map.file (C:\Users\Lorenzo\Documents\testElectron\my
> -project\node_modules\app-builder-lib\src\winPackager.ts:354:21)
>     at go$readdir$cb (C:\Users\Lorenzo\Documents\testElectron\my-project\node_mo
> dules\graceful-fs\graceful-fs.js:162:14)
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\winPackager.ts:352:27
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.signApp (C:\Users\Lorenzo\Documents\testElectron\my-project\n
> ode_modules\app-builder-lib\src\winPackager.ts:346:73)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\platformPackager.ts:250:16
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at WinPackager.doPack (C:\Users\Lorenzo\Documents\testElectron\my-project\no
> de_modules\app-builder-lib\src\platformPackager.ts:167:165)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\platformPackager.ts:113:16
>     at Generator.next (<anonymous>)
> From previous event:
>     at WinPackager.pack (C:\Users\Lorenzo\Documents\testElectron\my-project\node
> _modules\app-builder-lib\src\platformPackager.ts:111:95)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\packager.ts:406:24
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at Packager.doBuild (C:\Users\Lorenzo\Documents\testElectron\my-project\node
> _modules\app-builder-lib\src\packager.ts:372:24)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\packager.ts:342:57
>     at Generator.next (<anonymous>)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\graceful-
> fs\graceful-fs.js:111:16
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\graceful-
> fs\graceful-fs.js:45:10
>     at FSReqWrap.oncomplete (fs.js:135:15)
> From previous event:
>     at Packager._build (C:\Users\Lorenzo\Documents\testElectron\my-project\node_
> modules\app-builder-lib\src\packager.ts:311:133)
>     at C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\app-build
> er-lib\src\packager.ts:307:23
>     at Generator.next (<anonymous>)
>     at runCallback (timers.js:810:20)
>     at tryOnImmediate (timers.js:768:5)
>     at processImmediate [as _immediateCallback] (timers.js:745:5)
> From previous event:
>     at Packager.build (C:\Users\Lorenzo\Documents\testElectron\my-project\node_m
> odules\app-builder-lib\src\packager.ts:264:14)
>     at build (C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\ap
> p-builder-lib\src\index.ts:59:28)
>     at build (C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\el
> ectron-builder\src\builder.ts:227:10)
>     at then (C:\Users\Lorenzo\Documents\testElectron\my-project\node_modules\ele
> ctron-builder\src\cli\cli.ts:46:19)
>     at <anonymous>
> error Command failed with exit code 1.

##### Tell me about your development environment.
  * Node version: 8.12
  * NPM version: 6.4.1
  * Operating System: Windows 7

**Comment by loreberti89** [comment]
Solved with remove node modules and reinstall
